### ISSUE TITLE
Extended File Dialogs error 

### ISSUE THREAD

**Issue by herledant** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.50#2]
Hello Wanergp,

I'm facing to an error on line 30 of Extensions.cs file in Extended File Dialogs project.

> Error CS0161	'Extensions.ShowDialog(FileDialog, FileDialogControlBase, IWin32Window)' : path of code don't return all a value 

![image](https://user-images.githubusercontent.com/9166449/44004514-e393a2d6-9e63-11e8-9fe4-2c6a658b552d.png)

Many thank's for your help.

Best Regard's

**Comment by Wagnerp** [comment]
Hi @herledant 

The extended dialog code is incomplete, as I was trying to find a way to incorporate shell components, wrappers etc before focusing on other code in the toolkit. Maybe one day I can sort this out.

**Comment by herledant** [comment]
Ok
Thank's for quick answer!
;-)

**Comment by herledant** [comment]
Ok
Thank's for quick answer!
;-)
